### ISSUE TITLE
Add releases for Version 3.2 and version 2.3

### ISSUE THREAD

**Issue by jgadsden** [jgadsden/tin-whistle-tablature#27]
@DLLarson and @riaanvn I think it would be good to create release snapshots for the current MuseScore 3 (version 3.2.3) and  MuseScore 2 (currently version 2.3.2). This is a good time to do it, as we are looking at adding in support for Low Tin Whistles.

What tags should be used? Going by generally used naming conventions for Musescore plugins it should be 'v3.2.x' and 'v2.3.x', if you agree?

**Comment by riaanvn** [comment]
Hi @jgadsden

My suggestion

v3.2, since the official release seems to suppress z in vx.y.z if z = 0. E.g. they never release 3.2.0 nor do they refer to 3.2.x for referencing the 3.2 series. 
v2.3.2 - since that is the terminal v2.3 release. Unless you want to be super-inclusive, and have tested pre v2.3.2. In that case I would use v2.3.0

But the two you have listed are unlikely to be misunderstood.

**Comment by jgadsden** [comment]
Thanks @riaanvn  - these look good suggestions to me, and we can go with them.
