### ISSUE TITLE
Is it possible use CLI musescore command to convert from mscz D tin whistle tab to a pdf?

### ISSUE THREAD

**Issue by lets00** [jgadsden/tin-whistle-tablature#29]
Hi,
I want convert this file: [0001-Cooley\'s.zip](https://github.com/jgadsden/tin-whistle-tablature/files/4303382/0001-Cooley.s.zip) in a pdf file.

So, I create this job:
```json[
  {
    "in": "0001-Cooley\'s.mscz",
    "out": "0001-Cooley\'s.pdf",
    "plugin": "tin-whistle-tablature.qml"
  }
]
```

But, when I run this job (```mscore3 -j job.json```), the out file does not appear with fingering.
Is it possible, using CLI, convert this file to a pdf?

**Comment by jgadsden** [comment]
Hello @lets00 - could you check that you have the font installed? If you can see the tabs in MuseScore then the font is installed, otherwise here are the instructions:

`This plugin relies on a font being installed, which is not included in this download but can be obtained from [Blayne Chastain's site](https://www.blaynechastain.com/wp-content/uploads/TinWhistleTab.zip). If the font isn't installed you will be presented with a message box telling you how to obtain the font. To install the font, it is usually just a case of double-clicking the downloaded .ttf file and agreeing to the install process. If that does not work then on linux systems try copying the TinWhistleTab.ttf font file to the /usr/share/fonts/truetype/ directory.`

**Comment by jgadsden** [comment]
Hello @lets00 
I had a look at the score using the MuseScore 3 application, and get this message when applying the tabs: 
```
No selected staff in the current score uses a tin whistle instrument.
Use menu command "Edit -> Instruments" to select your instrument.
```
The staff shows that it is a 'D Tin Whistle', so I am not sure how this is happening. Do you mind if I reopen this issue?

**Comment by lets00** [comment]
Hi @jgadsden .
When I installed the TinWhistle font on my system, I managed to generate the PDF file. So, I thought it was a mistake on my part.

**Comment by jgadsden** [comment]
Ah, that must be it - and I found I was using an out of date tin whistle plugin just now, hence my error. All good and I will close this, cheers!
