### ISSUE TITLE
Plugin no longer works with Musescore 3.4.2

### ISSUE THREAD

**Issue by jebbgrenham** [jgadsden/tin-whistle-tablature#33]
Not sure if this project is abandoned or active, but the plugin does not work with current version of Musescore 3 (3.4.2). Musescore ignores it entirely and does not include it in the plugin manager.

**Comment by jebbgrenham** [comment]
Did a bit more tracing on this... the issue is not a bug on the software at all. It's a version (typographical) error at this page: https://musescore.org/en/project/tin-whistle-tablature
The Version 2 link downloads the VERSION 3 plugin.
The Version 3 link downloads the VERSION 2 plugin!

**Comment by jgadsden** [comment]
@jebbgrenham - many thanks for hunting this down, so easy for me to make a typo and unless anyone finds it ... it just stays there. I will fix up the MuseScore page now.

Definitely this project is active, we had an issue with Windows 10 and the font file last month which we fixed, so people seem to be  using it.

Closing this issue because I have fixed the download links.
