### ISSUE TITLE
Irish Tab does not appear when I try to choose "Add tablature" options

### ISSUE THREAD

**Issue by lets00** [jgadsden/tin-whistle-tablature#7]
Hi,

I am try to use your plugin to add a Irish D flute tablature on a music that I am writing but the tablature does not appear in the score.

I opened musescore via console and this options appear when I select plugin and try to choose "add tablature" option:
```
qml: hello tin whistle tablature
qml: Ms::Score(0x556bb2a6f400)
qml: Sem título
qml: Selected staves 1 - 1 - 46080
qml: Skipped staff 1 for instrument: wind.flutes.flute.irish
Signal QQmlEngine::quit() emitted, but no receivers connected to handle it.
```
My specs:
**OS**: Ubuntu 18.04.2
**Musescore version**: MuseScore2 2.3.2

**Comment by jgadsden** [comment]
Sorry about that - this is not an error I have seen before. I will have a look and see f there is anything I can do.

**Comment by jgadsden** [comment]
I have had a look and the tab is only for the Tin Whistle. There are 3 types of whistle supported:
* "wind.flutes.whistle.tin", the default is the whistle tuned to C (although the most common is tuned to D)
* "wind.flutes.whistle.tin.bflat", the whistle tuned to Bb
* "wind.flutes.whistle.tin.d", the whistle tuned to D
your staff is "wind.flutes.flute.irish" which is an actual flute not a tin whistle, so it is being skipped and no tabs applied.  Not sure why the line:
Qt.quit()
does not work for you, I guess it is because you are running from the console? Can you provide me with the score you are working on and the console command please?

**Comment by lets00** [comment]
Hmm. I add a new instrument called D Tin Whistle but I still can not add the tab.

> does not work for you, I guess it is because you are running from the console? Can you provide me with the score you are working on and the console command please?

Sure. The musescore file: https://musescore.com/user/15272/scores/5479026/s/plTRIN

In console, I just used the command:
```bash
$ mscore
```

**Comment by jgadsden** [comment]
I can not access your musescore file: https://musescore.com/user/15272/scores/5479026/s/plTRIN
I keep getting message "This score is unavailable". However I have added example scores to both Version 3 and Version 2 plugins - could you try the examples please to see if they work for your system?
Many thanks, Jon
